### ISSUE TITLE
Acronym Definition Correction

### ISSUE THREAD

**Issue by choicelildice** [DrupalSecurityTeam/drupalpcicompliance#41]
The document has the following in the acronym definition section:
"SCC: Acronym for “Security Standards Council,” it is the governing organization and
open forum responsible for the development, management, education, and awareness of PCI Security Standards."

The correct acronym (the correct one is used throughout the document) is "SSC."

**Comment by greggles** [comment]
I don't see SCC in the raw .md file: https://github.com/rickmanelius/drupalpcicompliance/blame/master/DrupalPCICompliance.md

Which line has this problem?

I did realize that AOC is not defined there and probably could/should be.

**Comment by rickmanelius** [comment]
Looks like the PDF is out of date/sync with this single character issue. Thanks for catching! https://github.com/rickmanelius/drupalpcicompliance/blob/master/DrupalPCICompliance.pdf

**Comment by greggles** [comment]
Since this is a problem in the PDF I think it will be fixed with a few other things when the PDF is generated. I added that as a task on #36 which is the last task in that milestone.
