### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by rcross** [DrupalSecurityTeam/drupalpcicompliance#48]
Its been several years since this paper has been updated. Any plans to revise it?

**Comment by greggles** [comment]
The original author group of Rick Manelius, Ned McClain and me is probably not in a position to do an update. I haven't checked with anyone to confirm that sense, but having this issue open for ~4 years seems like a good indication of it.

If new folks were interested in revising it that would be amazing! Probably posting a comment here offering to do the work is a first step. I would be happy to be involved and support that effort in whatever way I can (e.g. being a proofreader, granting access, strategizing on finding funding if needed, etc.).

**Comment by greggles** [comment]
There is a bit of a plan in the form of a [milestone](https://github.com/DrupalSecurityTeam/drupalpcicompliance/milestone/4) that lays out some immediate steps towards an update including some specific ideas on content. A small update to 3.2 could be a good first goal.

I see that PCI DSS v4.0 was released earlier this year [quick guide here](https://docs-prv.pcisecuritystandards.org/PCI%20DSS/Supporting%20Document/PCI_DSS-QRG-v4_0.pdf) and that would be a great new area to look into.

**Comment by greggles** [comment]
There's also #36 about the next revision (the 1.3 milestone) and then I filed #49 about the 4.0 update with a 1.4 milestone. So I think I'm going to close this.
